# Generated by Django 2.1.5 on 2019-02-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('pengalaman', models.CharField(max_length=100)),
                ('pesan', models.TextField(max_length=255)),
            ],
        ),
    ]
